// Download self-hosted Tajawal + Almarai subsets from Google Fonts and emit a
// local fonts.css that references the downloaded woff2 files (no network at
// export time). Run once; output committed to the repo.
import fs from 'node:fs'
import path from 'node:path'

const UA =
  'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36'
const OUT = process.argv[2]
if (!OUT) throw new Error('usage: node fetch-fonts.mjs <fontdir>')
fs.mkdirSync(OUT, { recursive: true })

const SOURCES = [
  ['Tajawal', 'https://fonts.googleapis.com/css2?family=Tajawal:wght@400;500;700;800;900&display=swap'],
  ['Almarai', 'https://fonts.googleapis.com/css2?family=Almarai:wght@400;700;800&display=swap'],
]

// Keep only the subsets we need for Arabic + Latin brand text.
const KEEP = new Set(['arabic', 'latin', 'latin-ext'])

const blockRe =
  /\/\*\s*([\w-]+)\s*\*\/\s*@font-face\s*\{([^}]*)\}/g
const fieldRe = (name) => new RegExp(`${name}:\\s*([^;]+);`)

let css = `/* Self-hosted Tajawal + Almarai — generated by tools/carousel scripts.\n   Do not edit by hand; re-run the font fetcher to regenerate. */\n`

for (const [family, url] of SOURCES) {
  const res = await fetch(url, { headers: { 'User-Agent': UA } })
  const sheet = await res.text()
  let m
  while ((m = blockRe.exec(sheet))) {
    const subset = m[1]
    if (!KEEP.has(subset)) continue
    const body = m[2]
    const weight = (body.match(fieldRe('font-weight')) || [])[1]?.trim()
    const style = (body.match(fieldRe('font-style')) || [])[1]?.trim() || 'normal'
    const range = (body.match(fieldRe('unicode-range')) || [])[1]?.trim()
    const srcUrl = (body.match(/url\((https:[^)]+)\)/) || [])[1]
    if (!srcUrl || !weight) continue
    const file = `${family.toLowerCase()}-${weight}-${subset}.woff2`
    const buf = Buffer.from(await (await fetch(srcUrl, { headers: { 'User-Agent': UA } })).arrayBuffer())
    fs.writeFileSync(path.join(OUT, file), buf)
    css += `@font-face {\n  font-family: '${family}';\n  font-style: ${style};\n  font-weight: ${weight};\n  font-display: swap;\n  src: url('./fonts/${file}') format('woff2');\n  unicode-range: ${range};\n}\n`
    console.log(`saved ${file} (${buf.length} bytes)`)
  }
}

fs.writeFileSync(path.join(path.dirname(OUT), 'fonts.css'), css)
console.log('wrote fonts.css')
