/**
 * Derives the document palette from the real logo artwork.
 *
 * The repo's DESIGN.md palette (olive #7A9A4A and friends) was ruled out by the
 * owner as not matching the actual brand, so the anchor colour is read straight
 * out of assets/logo.png — the green Africa brush stroke behind the helmet. That
 * guarantees the printed profile matches the stamp clients already have.
 *
 * PNG decoding lives in png.mjs — no image libraries are installed here.
 */
import { readFile, writeFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'
import { decodePng } from './png.mjs'

const here = dirname(fileURLToPath(import.meta.url))
const assets = join(here, 'assets')

const hex = (r, g, b) =>
  '#' + [r, g, b].map((v) => Math.round(v).toString(16).padStart(2, '0')).join('').toUpperCase()

/** Mix toward black (amount<0) or white (amount>0) — used to build the ramp. */
function shade(r, g, b, amount) {
  const t = amount < 0 ? 0 : 255
  const k = Math.abs(amount)
  return [r + (t - r) * k, g + (t - g) * k, b + (t - b) * k]
}

function main(pixels) {
  // Average every qualifying green pixel rather than taking the most common
  // one. The mark is a gradient (roughly #495A16 → #BECB96), so the modal
  // colour is whichever end happens to cover more area — the mean lands on the
  // mid-tone a viewer actually reads as "the brand green".
  let n = 0, R = 0, G = 0, B = 0
  for (let i = 0; i < pixels.length; i += 4) {
    const r = pixels[i], g = pixels[i + 1], b = pixels[i + 2], a = pixels[i + 3]
    if (a < 250) continue
    // Green-dominant, and clearly not the black linework or the white ground.
    const max = Math.max(r, g, b)
    const min = Math.min(r, g, b)
    if (g <= r || g <= b) continue
    if (max - min < 25) continue        // greyscale
    if (max < 60 || min > 220) continue // too dark / too pale
    n++; R += r; G += g; B += b
  }

  if (n === 0) throw new Error('no brand green found in logo')
  R /= n; G /= n; B /= n
  const brand = hex(R, G, B)

  // Build the ramp off that single anchor so every surface is provably related to
  // the logo rather than to a token file the owner says is wrong.
  const tokens = {
    '--brand': brand,
    '--brand-dk': hex(...shade(R, G, B, -0.42)),
    '--brand-dp': hex(...shade(R, G, B, -0.68)),
    '--brand-lt': hex(...shade(R, G, B, 0.55)),
    '--brand-pale': hex(...shade(R, G, B, 0.86)),
    // Deep forest for full-bleed dark pages — dark enough for white text to sing,
    // but still carrying the brand hue rather than collapsing to flat black.
    '--bush': hex(...shade(R, G, B, -0.83)),
    '--ink': '#141712',
    '--sand': '#F2ECDF',
    '--sand-dk': '#E3D9C4',
    '--paper': '#FFFFFF',
    '--stone': '#6E6A59',
    '--whatsapp': '#25D366',
    // Red-earth trail accent for the motorbike route, kept deliberately apart
    // from the safari green so the two ways to travel read as distinct. Fixed
    // rather than sampled — the logo carries no second colour to derive it from.
    '--trail': '#8A3A22',
    '--trail-pale': '#F0E2DC',
  }

  const css =
    '/* Generated by derive-palette.mjs from assets/logo.png — do not edit by hand. */\n' +
    ':root {\n' +
    Object.entries(tokens).map(([k, v]) => `  ${k}: ${v};`).join('\n') +
    '\n}\n'

  return { css, tokens, brand }
}

const buf = await readFile(join(assets, 'logo.png'))
const { pixels } = decodePng(buf)
const { css, tokens, brand } = main(pixels)
await writeFile(join(assets, 'palette.css'), css, 'utf8')

console.log(`brand green sampled from logo: ${brand}`)
for (const [k, v] of Object.entries(tokens)) console.log(`  ${k.padEnd(12)} ${v}`)
