-- Group 69: Booking links, hotel vouchers, and the editable proposal template
--
-- Three independent additions that share one migration group:
--
--   * booking_links      — a token-linked, shareable self-service booking form
--                          for a specific departure. Send the link over WhatsApp;
--                          the recipient fills their traveller details and the
--                          booking lands in `bookings`/`booking_travellers`
--                          exactly like a website booking (reuses the existing
--                          /api/departures/:id/book pipeline).
--
--   * hotel_vouchers     — one accommodation-booking voucher per hotel stay on a
--                          confirmed departure. Generated by walking the tour's
--                          itinerary (tour_days.accommodation_id), grouping
--                          consecutive nights at the same hotel into a single
--                          stay with check-in/check-out dates, room count and
--                          guest names. Each carries a public token so the hotel
--                          can view/print it, and an emailable status workflow
--                          (draft → sent → confirmed) — mirrors the
--                          traveller_agreements token/e-sign pattern (group_66).
--
--   * proposal_templates — the editable cover letter + client email that goes
--                          out with a quote proposal. Bilingual EN/AR, with
--                          [Placeholder] tokens the app substitutes at send
--                          time. Mirrors agreement_templates (group_66): a
--                          single active row edited in the admin back office.
--
-- Public read on all three happens server-side through the service-role client
-- (createAdminClient), which bypasses RLS — the same pattern the agreement and
-- quote token pages already use — so RLS here only needs an admin-manage gate.
--
-- Idempotent — safe to re-run. Run after group_68.

-- ── Booking links ─────────────────────────────────────────────────────────
create table if not exists booking_links (
  id uuid primary key default gen_random_uuid(),
  departure_id uuid not null references departures(id) on delete cascade,
  token uuid unique not null default gen_random_uuid(),
  label text,                                     -- e.g. "WhatsApp enquiry — Ahmed"
  language text not null default 'en' check (language in ('en', 'ar')),
  max_bookings integer check (max_bookings is null or max_bookings > 0),
  use_count integer not null default 0 check (use_count >= 0),
  expires_at timestamptz,
  is_active boolean not null default true,
  created_by uuid,                                -- auth.users id of the admin
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_booking_links_departure_id on booking_links(departure_id);
create index if not exists idx_booking_links_token on booking_links(token);

drop trigger if exists update_booking_links_updated_at on booking_links;
create trigger update_booking_links_updated_at before update on booking_links
  for each row execute function update_updated_at_column();

-- ── Hotel vouchers ────────────────────────────────────────────────────────
-- Human-friendly, monotonic voucher numbers: HV-000001, HV-000002, …
create sequence if not exists hotel_voucher_number_seq;

create table if not exists hotel_vouchers (
  id uuid primary key default gen_random_uuid(),
  voucher_number text unique not null
    default 'HV-' || lpad(nextval('hotel_voucher_number_seq')::text, 6, '0'),
  token uuid unique not null default gen_random_uuid(),

  -- What this voucher belongs to. departure_id is the usual anchor; booking_id
  -- and quote_id are optional links for provenance/reporting.
  departure_id uuid references departures(id) on delete cascade,
  booking_id uuid references bookings(id) on delete set null,
  quote_id uuid references quotes(id) on delete set null,
  accommodation_id uuid references accommodations(id) on delete set null,

  -- Snapshotted hotel identity, so the voucher stays intact even if the
  -- accommodation record is later edited or removed.
  hotel_name text not null,
  hotel_email text,

  -- Stay details.
  check_in date not null,
  check_out date not null,
  nights integer not null check (nights > 0),
  num_rooms integer not null default 1 check (num_rooms > 0),
  room_type text,
  num_guests integer not null default 1 check (num_guests > 0),
  guest_names jsonb not null default '[]'::jsonb,   -- ["Ahmed Ali", "Sara Ali"]
  meal_plan text,                                    -- e.g. "Bed & Breakfast"
  special_requests text,
  internal_notes text,

  -- Workflow.
  status text not null default 'draft'
    check (status in ('draft', 'sent', 'confirmed', 'cancelled')),
  language text not null default 'en' check (language in ('en', 'ar')),
  hotel_confirmation_ref text,                       -- hotel's own booking ref
  sent_at timestamptz,
  confirmed_at timestamptz,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_hotel_vouchers_departure_id on hotel_vouchers(departure_id);
create index if not exists idx_hotel_vouchers_accommodation_id on hotel_vouchers(accommodation_id);
create index if not exists idx_hotel_vouchers_status on hotel_vouchers(status);
create index if not exists idx_hotel_vouchers_token on hotel_vouchers(token);

drop trigger if exists update_hotel_vouchers_updated_at on hotel_vouchers;
create trigger update_hotel_vouchers_updated_at before update on hotel_vouchers
  for each row execute function update_updated_at_column();

-- ── Proposal template (editable cover letter + client email) ──────────────
create table if not exists proposal_templates (
  id uuid primary key default gen_random_uuid(),
  title text not null default 'Default proposal template',

  -- Cover letter shown at the top of the client-facing proposal.
  cover_intro_en text,
  cover_intro_ar text,

  -- Email that carries the proposal link.
  email_subject_en text,
  email_subject_ar text,
  email_message_en text,
  email_message_ar text,
  email_signature_en text,
  email_signature_ar text,

  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists update_proposal_templates_updated_at on proposal_templates;
create trigger update_proposal_templates_updated_at before update on proposal_templates
  for each row execute function update_updated_at_column();

-- Seed one editable default row (only if the table is empty), with the same
-- [Placeholder] tokens the SafariOffice-style editor uses.
insert into proposal_templates (
  title,
  cover_intro_en, cover_intro_ar,
  email_subject_en, email_subject_ar,
  email_message_en, email_message_ar,
  email_signature_en, email_signature_ar
)
select
  'Default proposal template',
  E'Dear [Client Full Name],\n\nThank you for your inquiry. It is our pleasure to send you a custom-made quote for our [Tour Title] as per your request.\n\nThe tour begins on [Start Date] in [Start Destination] and runs for [Number of Days] days.\n\nPlease do not hesitate to contact us if you have any questions. We look forward to helping you plan your safari trip of a lifetime.\n\nBest regards',
  E'عزيزي [Client Full Name]،\n\nشكراً لاستفسارك. يسعدنا أن نرسل إليك عرض سعر مُصمّماً خصيصاً لرحلة [Tour Title] بناءً على طلبك.\n\nتبدأ الرحلة في [Start Date] من [Start Destination] وتستمر لمدة [Number of Days] أيام.\n\nلا تتردد في التواصل معنا لأي استفسار. نتطلع لمساعدتك في التخطيط لرحلة السفاري التي تحلم بها.\n\nمع أطيب التحيات',
  'Your safari proposal is ready',
  'عرض رحلة السفاري الخاص بك جاهز',
  E'Hello [Client Full Name],\n\nYour proposal for [Tour Title] is ready to view. Click the button below to open your personalised itinerary and pricing.',
  E'مرحباً [Client Full Name]،\n\nأصبح عرض رحلة [Tour Title] جاهزاً للاطلاع. اضغط على الزر أدناه لعرض برنامج رحلتك والأسعار الخاصة بك.',
  E'Best regards,\nSafari Adventure Riders\ninfo@safariadventureriders.com',
  E'مع أطيب التحيات،\nSafari Adventure Riders\ninfo@safariadventureriders.com'
where not exists (select 1 from proposal_templates);

-- ── RLS: admin-manage only (public/token reads go through service role) ───
alter table booking_links enable row level security;
alter table hotel_vouchers enable row level security;
alter table proposal_templates enable row level security;

drop policy if exists "Admins can manage booking_links" on booking_links;
create policy "Admins can manage booking_links" on booking_links
  for all to authenticated
  using (public.is_admin_user())
  with check (public.is_admin_user());

drop policy if exists "Admins can manage hotel_vouchers" on hotel_vouchers;
create policy "Admins can manage hotel_vouchers" on hotel_vouchers
  for all to authenticated
  using (public.is_admin_user())
  with check (public.is_admin_user());

drop policy if exists "Admins can manage proposal_templates" on proposal_templates;
create policy "Admins can manage proposal_templates" on proposal_templates
  for all to authenticated
  using (public.is_admin_user())
  with check (public.is_admin_user());
